version: "3.7"
services:
  api_service:
    build: .
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/framework?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: framework
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

networks:
  springapimysql-net:
    driver: bridge